#!/usr/bin/env php
<?php

require_once __DIR__ .'/vendor/autoload.php';

use Symfony\Component\Console\Application;

$app = new Application('Wordpress Password Generator', '1.0.0');
$app->addCommands([
    new \PasswordGen\Command\HashCommand('pass:hash'),
    new \PasswordGen\Command\CheckCommand('pass:check'),
]);

$app->run();
